language: python
python:
  - '2.7'
  - '3.6'
sudo: required
install:
  - pip install -e .[dev]
script: 
  - pipdeptree
  - pytest --cov=opentargets_urlzsource --cov-report term tests/ --fulltrace
deploy:
  provider: pypi
  skip_existing: true
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true
  distributions: "sdist bdist_wheel"

notifications:
  email:
    recipients:
    - ops@opentargets.org
    on_success: never
    on_failure: always
after_success:
  - codecov
